export const letters = [
  {
    name: "Haoming",
    email: "albinorabbithunter@gmail.com",
    title: "This is Test1",
    plaintext:
      "Dear FutureMe,Hello. You found this website on stumbleupon just now and this looked pretty cool. Here's a little rundown on your life right now:You graduated from Ohio State in June and you're still struggling to find a full-time job despite filling out many applications and having a failed job interview (the staff seemed stuck-up anyways). You are living at home in Napoleon and are starting to feel defeated, but by the time you get this letter, I know you will have found something. I hope you enjoy it!You have finally gained the courage to come out to your family and although you have to live away from Rachel right now, you plan on being with her as soon as you can afford a place together. The whole unemployment thing is depressing but knowing your life together is waiting for you gives you encouragement and hope. You always think of the awesome life you have ahead of you and how lucky you were to find someone you love so young.I hope by the time you get this letter you will be financially stable, are living in a house you picked out with Rachel and are in the process of having children or already have them. This all seems impossible now (being 23 and having no job and all) but I bet time is going to go a lot faster than you think.Writing this letter seems a little corny, but I'm sure you're enjoying reading it right now. Referring to my future self is a little odd right now, but I couldn't really think of any other way to say it...I hope everyone you love is healthy and happy. I hope you've learned to overcome some of your fears. I hope the government has allowed you to marry Rachel.You've come over a lot in your life and I hope you're living your life to the fullest. Nothing is more important than love and family and I hope you have cherished every moment of the people in your life and continue to do so.Love,Your 23 year old self",
    htmlcontent:
      "<p>Dear FutureMe,</p><p>Hello. You found this website on stumbleupon just now and this looked pretty cool. Here's a little rundown on your life right now:</p><p>You graduated from Ohio State in June and you're still struggling to find a full-time job despite filling out many applications and having a failed job interview (the staff seemed stuck-up anyways). You are living at home in Napoleon and are starting to feel defeated, but by the time you get this letter, I know you will have found something. I hope you enjoy it!</p><p>You have finally gained the courage to come out to your family and although you have to live away from Rachel right now, you plan on being with her as soon as you can afford a place together. The whole unemployment thing is depressing but knowing your life together is waiting for you gives you encouragement and hope. You always think of the awesome life you have ahead of you and how lucky you were to find someone you love so young.</p><p>I hope by the time you get this letter you will be financially stable, are living in a house you picked out with Rachel and are in the process of having children or already have them. This all seems impossible now (being 23 and having no job and all) but I bet time is going to go a lot faster than you think.</p><p>Writing this letter seems a little corny, but I'm sure you're enjoying reading it right now. Referring to my future self is a little odd right now, but I couldn't really think of any other way to say it...</p><p>I hope everyone you love is healthy and happy. I hope you've learned to overcome some of your fears. I hope the government has allowed you to marry Rachel.</p><p>You've come over a lot in your life and I hope you're living your life to the fullest. Nothing is more important than love and family and I hope you have cherished every moment of the people in your life and continue to do so.</p><p>Love,Your 23 year old self</p>",
    date: new Date(),
    flag: 1,
    likes: [],
    unlikes: [],
  },
  {
    name: "Haoming1",
    email: "albinorabbithunter1@gmail.com",
    title: "This is Test2",
    plaintext:
      "Dear FutureMe,Hello. You found this website on stumbleupon just now and this looked pretty cool. Here's a little rundown on your life right now:You graduated from Ohio State in June and you're still struggling to find a full-time job despite filling out many applications and having a failed job interview (the staff seemed stuck-up anyways). You are living at home in Napoleon and are starting to feel defeated, but by the time you get this letter, I know you will have found something. I hope you enjoy it!You have finally gained the courage to come out to your family and although you have to live away from Rachel right now, you plan on being with her as soon as you can afford a place together. The whole unemployment thing is depressing but knowing your life together is waiting for you gives you encouragement and hope. You always think of the awesome life you have ahead of you and how lucky you were to find someone you love so young.I hope by the time you get this letter you will be financially stable, are living in a house you picked out with Rachel and are in the process of having children or already have them. This all seems impossible now (being 23 and having no job and all) but I bet time is going to go a lot faster than you think.Writing this letter seems a little corny, but I'm sure you're enjoying reading it right now. Referring to my future self is a little odd right now, but I couldn't really think of any other way to say it...I hope everyone you love is healthy and happy. I hope you've learned to overcome some of your fears. I hope the government has allowed you to marry Rachel.You've come over a lot in your life and I hope you're living your life to the fullest. Nothing is more important than love and family and I hope you have cherished every moment of the people in your life and continue to do so.Love,Your 23 year old self",
    htmlcontent:
      "<p>Dear FutureMe,</p><p>Hello. You found this website on stumbleupon just now and this looked pretty cool. Here's a little rundown on your life right now:</p><p>You graduated from Ohio State in June and you're still struggling to find a full-time job despite filling out many applications and having a failed job interview (the staff seemed stuck-up anyways). You are living at home in Napoleon and are starting to feel defeated, but by the time you get this letter, I know you will have found something. I hope you enjoy it!</p><p>You have finally gained the courage to come out to your family and although you have to live away from Rachel right now, you plan on being with her as soon as you can afford a place together. The whole unemployment thing is depressing but knowing your life together is waiting for you gives you encouragement and hope. You always think of the awesome life you have ahead of you and how lucky you were to find someone you love so young.</p><p>I hope by the time you get this letter you will be financially stable, are living in a house you picked out with Rachel and are in the process of having children or already have them. This all seems impossible now (being 23 and having no job and all) but I bet time is going to go a lot faster than you think.</p><p>Writing this letter seems a little corny, but I'm sure you're enjoying reading it right now. Referring to my future self is a little odd right now, but I couldn't really think of any other way to say it...</p><p>I hope everyone you love is healthy and happy. I hope you've learned to overcome some of your fears. I hope the government has allowed you to marry Rachel.</p><p>You've come over a lot in your life and I hope you're living your life to the fullest. Nothing is more important than love and family and I hope you have cherished every moment of the people in your life and continue to do so.</p><p>Love,Your 23 year old self</p>",
    date: new Date(),
    flag: 3,
    likes: [],
    unlikes: [],
  },
  {
    name: "Haoming",
    email: "albinorabbithunter@gmail.com",
    title: "Test 2 content",
    plaintext:
      "Dear FutureMe,Hello. You found this website on stumbleupon just now and this looked pretty cool. Here's a little rundown on your life right now:You graduated from Ohio State in June and you're still struggling to find a full-time job despite filling out many applications and having a failed job interview (the staff seemed stuck-up anyways). You are living at home in Napoleon and are starting to feel defeated, but by the time you get this letter, I know you will have found something. I hope you enjoy it!You have finally gained the courage to come out to your family and although you have to live away from Rachel right now, you plan on being with her as soon as you can afford a place together. The whole unemployment thing is depressing but knowing your life together is waiting for you gives you encouragement and hope. You always think of the awesome life you have ahead of you and how lucky you were to find someone you love so young.I hope by the time you get this letter you will be financially stable, are living in a house you picked out with Rachel and are in the process of having children or already have them. This all seems impossible now (being 23 and having no job and all) but I bet time is going to go a lot faster than you think.Writing this letter seems a little corny, but I'm sure you're enjoying reading it right now. Referring to my future self is a little odd right now, but I couldn't really think of any other way to say it...I hope everyone you love is healthy and happy. I hope you've learned to overcome some of your fears. I hope the government has allowed you to marry Rachel.You've come over a lot in your life and I hope you're living your life to the fullest. Nothing is more important than love and family and I hope you have cherished every moment of the people in your life and continue to do so.Love,Your 23 year old self",
    htmlcontent:
      "<p>Dear FutureMe,</p><p>Hello. You found this website on stumbleupon just now and this looked pretty cool. Here's a little rundown on your life right now:</p><p>You graduated from Ohio State in June and you're still struggling to find a full-time job despite filling out many applications and having a failed job interview (the staff seemed stuck-up anyways). You are living at home in Napoleon and are starting to feel defeated, but by the time you get this letter, I know you will have found something. I hope you enjoy it!</p><p>You have finally gained the courage to come out to your family and although you have to live away from Rachel right now, you plan on being with her as soon as you can afford a place together. The whole unemployment thing is depressing but knowing your life together is waiting for you gives you encouragement and hope. You always think of the awesome life you have ahead of you and how lucky you were to find someone you love so young.</p><p>I hope by the time you get this letter you will be financially stable, are living in a house you picked out with Rachel and are in the process of having children or already have them. This all seems impossible now (being 23 and having no job and all) but I bet time is going to go a lot faster than you think.</p><p>Writing this letter seems a little corny, but I'm sure you're enjoying reading it right now. Referring to my future self is a little odd right now, but I couldn't really think of any other way to say it...</p><p>I hope everyone you love is healthy and happy. I hope you've learned to overcome some of your fears. I hope the government has allowed you to marry Rachel.</p><p>You've come over a lot in your life and I hope you're living your life to the fullest. Nothing is more important than love and family and I hope you have cherished every moment of the people in your life and continue to do so.</p><p>Love,Your 23 year old self</p>",
    date: new Date(),
    flag: 2,
    likes: [],
    unlikes: [],
  },
  {
    name: "Haoming1",
    email: "albinorabbithunter1@gmail.com",
    title: "Test 2 content",
    plaintext:
      "Dear FutureMe,Hello. You found this website on stumbleupon just now and this looked pretty cool. Here's a little rundown on your life right now:You graduated from Ohio State in June and you're still struggling to find a full-time job despite filling out many applications and having a failed job interview (the staff seemed stuck-up anyways). You are living at home in Napoleon and are starting to feel defeated, but by the time you get this letter, I know you will have found something. I hope you enjoy it!You have finally gained the courage to come out to your family and although you have to live away from Rachel right now, you plan on being with her as soon as you can afford a place together. The whole unemployment thing is depressing but knowing your life together is waiting for you gives you encouragement and hope. You always think of the awesome life you have ahead of you and how lucky you were to find someone you love so young.I hope by the time you get this letter you will be financially stable, are living in a house you picked out with Rachel and are in the process of having children or already have them. This all seems impossible now (being 23 and having no job and all) but I bet time is going to go a lot faster than you think.Writing this letter seems a little corny, but I'm sure you're enjoying reading it right now. Referring to my future self is a little odd right now, but I couldn't really think of any other way to say it...I hope everyone you love is healthy and happy. I hope you've learned to overcome some of your fears. I hope the government has allowed you to marry Rachel.You've come over a lot in your life and I hope you're living your life to the fullest. Nothing is more important than love and family and I hope you have cherished every moment of the people in your life and continue to do so.Love,Your 23 year old self",
    htmlcontent:
      "<p>Dear FutureMe,</p><p>Hello. You found this website on stumbleupon just now and this looked pretty cool. Here's a little rundown on your life right now:</p><p>You graduated from Ohio State in June and you're still struggling to find a full-time job despite filling out many applications and having a failed job interview (the staff seemed stuck-up anyways). You are living at home in Napoleon and are starting to feel defeated, but by the time you get this letter, I know you will have found something. I hope you enjoy it!</p><p>You have finally gained the courage to come out to your family and although you have to live away from Rachel right now, you plan on being with her as soon as you can afford a place together. The whole unemployment thing is depressing but knowing your life together is waiting for you gives you encouragement and hope. You always think of the awesome life you have ahead of you and how lucky you were to find someone you love so young.</p><p>I hope by the time you get this letter you will be financially stable, are living in a house you picked out with Rachel and are in the process of having children or already have them. This all seems impossible now (being 23 and having no job and all) but I bet time is going to go a lot faster than you think.</p><p>Writing this letter seems a little corny, but I'm sure you're enjoying reading it right now. Referring to my future self is a little odd right now, but I couldn't really think of any other way to say it...</p><p>I hope everyone you love is healthy and happy. I hope you've learned to overcome some of your fears. I hope the government has allowed you to marry Rachel.</p><p>You've come over a lot in your life and I hope you're living your life to the fullest. Nothing is more important than love and family and I hope you have cherished every moment of the people in your life and continue to do so.</p><p>Love,Your 23 year old self</p>",
    date: new Date(),
    flag: 2,
    likes: [],
    unlikes: [],
  },
  {
    name: "Haoming",
    email: "albinorabbithunter@gmail.com",
    title: "This is Test5",
    plaintext:
      "Dear FutureMe,Hello. You found this website on stumbleupon just now and this looked pretty cool. Here's a little rundown on your life right now:You graduated from Ohio State in June and you're still struggling to find a full-time job despite filling out many applications and having a failed job interview (the staff seemed stuck-up anyways). You are living at home in Napoleon and are starting to feel defeated, but by the time you get this letter, I know you will have found something. I hope you enjoy it!You have finally gained the courage to come out to your family and although you have to live away from Rachel right now, you plan on being with her as soon as you can afford a place together. The whole unemployment thing is depressing but knowing your life together is waiting for you gives you encouragement and hope. You always think of the awesome life you have ahead of you and how lucky you were to find someone you love so young.I hope by the time you get this letter you will be financially stable, are living in a house you picked out with Rachel and are in the process of having children or already have them. This all seems impossible now (being 23 and having no job and all) but I bet time is going to go a lot faster than you think.Writing this letter seems a little corny, but I'm sure you're enjoying reading it right now. Referring to my future self is a little odd right now, but I couldn't really think of any other way to say it...I hope everyone you love is healthy and happy. I hope you've learned to overcome some of your fears. I hope the government has allowed you to marry Rachel.You've come over a lot in your life and I hope you're living your life to the fullest. Nothing is more important than love and family and I hope you have cherished every moment of the people in your life and continue to do so.Love,Your 23 year old self",
    htmlcontent:
      "<p>Dear FutureMe,</p><p>Hello. You found this website on stumbleupon just now and this looked pretty cool. Here's a little rundown on your life right now:</p><p>You graduated from Ohio State in June and you're still struggling to find a full-time job despite filling out many applications and having a failed job interview (the staff seemed stuck-up anyways). You are living at home in Napoleon and are starting to feel defeated, but by the time you get this letter, I know you will have found something. I hope you enjoy it!</p><p>You have finally gained the courage to come out to your family and although you have to live away from Rachel right now, you plan on being with her as soon as you can afford a place together. The whole unemployment thing is depressing but knowing your life together is waiting for you gives you encouragement and hope. You always think of the awesome life you have ahead of you and how lucky you were to find someone you love so young.</p><p>I hope by the time you get this letter you will be financially stable, are living in a house you picked out with Rachel and are in the process of having children or already have them. This all seems impossible now (being 23 and having no job and all) but I bet time is going to go a lot faster than you think.</p><p>Writing this letter seems a little corny, but I'm sure you're enjoying reading it right now. Referring to my future self is a little odd right now, but I couldn't really think of any other way to say it...</p><p>I hope everyone you love is healthy and happy. I hope you've learned to overcome some of your fears. I hope the government has allowed you to marry Rachel.</p><p>You've come over a lot in your life and I hope you're living your life to the fullest. Nothing is more important than love and family and I hope you have cherished every moment of the people in your life and continue to do so.</p><p>Love,Your 23 year old self</p>",
    date: new Date(),
    flag: 1,
    likes: [],
    unlikes: [],
  },
  {
    name: "Haoming1",
    email: "albinorabbithunter1@gmail.com",
    title: "This is Test6",
    plaintext:
      "Dear FutureMe,Hello. You found this website on stumbleupon just now and this looked pretty cool. Here's a little rundown on your life right now:You graduated from Ohio State in June and you're still struggling to find a full-time job despite filling out many applications and having a failed job interview (the staff seemed stuck-up anyways). You are living at home in Napoleon and are starting to feel defeated, but by the time you get this letter, I know you will have found something. I hope you enjoy it!You have finally gained the courage to come out to your family and although you have to live away from Rachel right now, you plan on being with her as soon as you can afford a place together. The whole unemployment thing is depressing but knowing your life together is waiting for you gives you encouragement and hope. You always think of the awesome life you have ahead of you and how lucky you were to find someone you love so young.I hope by the time you get this letter you will be financially stable, are living in a house you picked out with Rachel and are in the process of having children or already have them. This all seems impossible now (being 23 and having no job and all) but I bet time is going to go a lot faster than you think.Writing this letter seems a little corny, but I'm sure you're enjoying reading it right now. Referring to my future self is a little odd right now, but I couldn't really think of any other way to say it...I hope everyone you love is healthy and happy. I hope you've learned to overcome some of your fears. I hope the government has allowed you to marry Rachel.You've come over a lot in your life and I hope you're living your life to the fullest. Nothing is more important than love and family and I hope you have cherished every moment of the people in your life and continue to do so.Love,Your 23 year old self",
    htmlcontent:
      "<h1><strong>Dear, FutureMe.</strong></h1><p><strong>How are you.</strong></p><p><strong>My name is XianZhu Li.</strong></p>     <p><strong>I am from china.</strong></p><p><strong>I am a senior Full stack developer who has good experience with React and JavaScript.</strong></p><p><strong><em>I would like to work with you.</em></strong></p>",
    date: new Date(),
    flag: 1,
    likes: [],
    unlikes: [],
  },
];
